2022/03/02_演習5_1回目_進捗率100％
ddt-hosoya/database_design pull request #5
Opened 2022-03-02 13:10 UTC by ddt-hosoya

2022-03-23 10:46 UTC, ddt-mentor commented on database_design/src/work05/work05_01.txt
> +						支店商品.支店コード AS 支店コード, 支店.支店名 AS 支店名,  COUNT(*) AS 商品数
柴田
サブクエリ側に支店名は不要では？

2022-03-23 10:52 UTC, ddt-mentor commented on database_design/src/work05/work05_02.txt
> +	;
柴田
もっと簡単になりません？商品数が最大の支店情報であればいいので。

2022-03-23 11:51 UTC, ddt-hosoya commented on database_design/src/work05/work05_01.txt
> +						支店商品.支店コード AS 支店コード, 支店.支店名 AS 支店名,  COUNT(*) AS 商品数
支店コードだけでは一意にならないため、支店名か支社コードのどちらかは必要になります。

2022-03-23 12:58 UTC, ddt-mentor requested changes

2022-03-23 12:58 UTC, ddt-mentor commented on database_design/src/work05/work05_02.txt
> +		支店商品.商品数 = (SELECT MAX(商品数) FROM 支店商品)
柴田
もう一声ください。サブクエリは不用になりませんかね？
※最大を取得する　というWhere句にはならないと思いますが、同様の結果が得られるはずです。

2022-03-23 12:58 UTC, ddt-mentor commented on database_design/src/work05/work05_01.txt
> +						支店商品.支店コード AS 支店コード, 支店.支店名 AS 支店名,  COUNT(*) AS 商品数
柴田
"支店"コードと"支店"名ですが一意になりますか？
（元々は同じ意味のデータでは？という所から来た指摘でしたが…）
支店名はキー項目ではないはずで、一意を特定するための値としては不適切かと思います。

2022-04-13 12:27 UTC, ddt-hosoya commented on database_design/src/work05/work05_01.txt
> +						支店商品.支店コード AS 支店コード, 支店.支店名 AS 支店名,  COUNT(*) AS 商品数
細谷
支店テーブルの支社コードと支店コードで一意の支店名が取れる認識です。後で口頭で説明させてください。

2022-04-27 12:05 UTC, ddt-mentor commented on database_design/src/work05/work05_01.txt
> +						支店商品.支店コード AS 支店コード, 支店.支店名 AS 支店名,  COUNT(*) AS 商品数
成田
支店テーブルの支社コードと支店コードで一意の支店名が取れる。
支店コードのみでは一意にならない。
支社コードを取得してもよいが、最終的に出力するのは支店コードと支店名のため、それにあわせて支店名をしゅとくしたとのこと。
よって問題ないとする。

2022-04-27 12:05 UTC, ddt-mentor commented
成田
確認しました。問題ありません。

2022-05-11 11:14 UTC, merged